version: '3.8'
services:
  pol2yaml:
    build:
      context: .
      dockerfile: antlr4.Dockerfile
      args:
        INSTALL_MAVEN: "true"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity