version: '3.8'
services:
  pol2yaml:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-18-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  antlr4:
    build:
      context: .
      dockerfile: antlr4.Dockerfile
      args:
        INSTALL_MAVEN: "true"
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity